apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stackapps.fullname" . }}
  labels:
    {{- include "stackapps.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "stackapps.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "stackapps.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "stackapps.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: manager
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /manager
        args:
      {{- if .Values.enableLeaderElection }}
        - --enable-leader-election
      {{- end }}
        env:
        - name: ENABLE_WEBHOOKS
          value: "{{ .Values.webhooks.enabled }}"
      {{- if .Values.webhooks.enabled }}
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.webhooks.enabled }}
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: stackapps-webhook-cert
    {{- end }}
