{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stackapps.serviceAccountName" . }}
  labels:
{{ include "stackapps.labels" . | nindent 4 }}
{{- end -}}
