apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: traefik-ingress-lb
    name: traefik-ingress-lb
  name: traefik
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: traefik
    nodePort: 30395
    port: 9000
    protocol: TCP
    targetPort: traefik
  - name: web
    nodePort: 30001
    port: 80
    protocol: TCP
    targetPort: web
  - name: websecure
    nodePort: 30503
    port: 443
    protocol: TCP
    targetPort: websecure
  selector:
    k8s-app: traefik-ingress-lb                                                                                                                                                                                                    
    name: traefik-ingress-lb  
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

